export const leagues = {
	response: [
		{
			league: [
				{
					id: 4,
					name: 'Euro Championship',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/4.png',
				},
				{
					id: 1,
					name: 'World Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/1.png',
				},
				{
					id: 8,
					name: 'World Cup - Women',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/8.png',
				},
				{
					id: 2,
					name: 'UEFA Champions League',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/2.png',
				},
				{
					id: 3,
					name: 'UEFA Europa League',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/3.png',
				},
				{
					id: 15,
					name: 'FIFA Club World Cup',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/15.png',
				},
				{
					id: 6,
					name: 'Africa Cup of Nations',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/6.png',
				},
				{
					id: 9,
					name: 'Copa America',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/9.png',
				},
			],
			country: {
				name: 'World',
				code: null,
				flag: null,
			},
		},

		{
			league: [
				{
					id: 61,
					name: 'Ligue 1',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/61.png',
				},
				{
					id: 62,
					name: 'Ligue 2',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/62.png',
				},
				{
					id: 66,
					name: 'Coupe de France',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/66.png',
				},
				{
					id: 65,
					name: 'Coupe de la Ligue',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/65.png',
				},
			],
			country: {
				name: 'France',
				code: 'FR',
				flag: 'https://media.api-sports.io/flags/fr.svg',
			},
		},

		{
			league: [
				{
					id: 144,
					name: 'Jupiler Pro League',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/144.png',
				},
			],
			country: {
				name: 'Belgium',
				code: 'BE',
				flag: 'https://media.api-sports.io/flags/be.svg',
			},

			seasons: [
				{
					year: 2010,
					start: '2010-07-30',
					end: '2011-05-16',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-07-29',
					end: '2012-05-20',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-07-28',
					end: '2013-05-26',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-07-26',
					end: '2014-05-18',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-07-25',
					end: '2015-05-31',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-07-24',
					end: '2016-05-29',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-07-29',
					end: '2017-05-21',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-07-28',
					end: '2018-05-20',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-07-27',
					end: '2019-05-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-07-26',
					end: '2020-03-15',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-08-08',
					end: '2021-05-23',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 71,
					name: 'Serie A',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/71.png',
				},
				{
					id: 72,
					name: 'Serie B',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/72.png',
				},
				{
					id: 75,
					name: 'Serie C',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/72.png',
				},
			],
			country: {
				name: 'Brazil',
				code: 'BR',
				flag: 'https://media.api-sports.io/flags/br.svg',
			},

			seasons: [
				{
					year: 2010,
					start: '2010-05-08',
					end: '2010-11-28',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-05-21',
					end: '2011-12-04',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-05-19',
					end: '2012-12-02',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-05-25',
					end: '2013-12-08',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-04-19',
					end: '2014-12-07',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-05-09',
					end: '2015-12-06',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-05-14',
					end: '2016-12-11',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-05-13',
					end: '2017-12-03',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-04-14',
					end: '2018-12-02',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-04-27',
					end: '2019-12-08',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-08-08',
					end: '2021-02-26',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2021,
					start: '2021-05-30',
					end: '2021-12-05',
					current: true,
					coverage: {
						fixtures: {
							events: false,
							lineups: false,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
			],
		},

		{
			league: [
				{
					id: 39,
					name: 'Premier League',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/39.png',
				},
				{
					id: 40,
					name: 'Championship',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/40.png',
				},
				{
					id: 46,
					name: 'EFL Trophy',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/46.png',
				},
				{
					id: 45,
					name: 'FA Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/45.png',
				},
				{
					id: 48,
					name: 'League Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/48.png',
				},
				{
					id: 528,
					name: 'Community Shield',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/528.png',
				},
			],
			country: {
				name: 'England',
				code: 'GB',
				flag: 'https://media.api-sports.io/flags/gb.svg',
			},
			seasons: [
				{
					year: 2010,
					start: '2010-08-14',
					end: '2011-05-17',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-08-13',
					end: '2012-05-13',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-08-18',
					end: '2013-05-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-08-17',
					end: '2014-05-11',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-08-16',
					end: '2015-05-24',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-08-08',
					end: '2016-05-17',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-08-13',
					end: '2017-05-21',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-11',
					end: '2018-05-13',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-08-10',
					end: '2019-05-12',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-08-09',
					end: '2020-07-26',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-09-12',
					end: '2021-05-23',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 78,
					name: 'Bundesliga 1',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/78.png',
				},
				{
					id: 79,
					name: 'Bundesliga 2',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/79.png',
				},
				{
					id: 529,
					name: 'Super Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/529.png',
				},
				{
					id: 81,
					name: 'DFB Pokal',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/81.png',
				},
			],
			country: {
				name: 'Germany',
				code: 'DE',
				flag: 'https://media.api-sports.io/flags/de.svg',
			},
			seasons: [
				{
					year: 2010,
					start: '2010-08-20',
					end: '2011-05-14',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-08-05',
					end: '2012-05-05',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-08-24',
					end: '2013-05-18',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-08-09',
					end: '2014-05-10',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-08-22',
					end: '2015-05-23',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-08-14',
					end: '2016-05-14',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-08-26',
					end: '2017-05-20',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-18',
					end: '2018-05-12',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-08-24',
					end: '2019-05-27',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-08-16',
					end: '2020-07-06',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-09-18',
					end: '2021-05-22',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 135,
					name: 'Serie A',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/135.png',
				},
				{
					id: 136,
					name: 'Serie B',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/547.png',
				},
				{
					id: 547,
					name: 'Super Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/547.png',
				},
				{
					id: 136,
					name: 'Serie B',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/136.png',
				},
				{
					id: 137,
					name: 'Coppa Italia',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/137.png',
				},
			],
			country: {
				name: 'Italy',
				code: 'IT',
				flag: 'https://media.api-sports.io/flags/it.svg',
			},
			seasons: [
				{
					year: 2010,
					start: '2010-08-28',
					end: '2011-05-22',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-09-09',
					end: '2012-05-13',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-08-25',
					end: '2013-05-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-08-24',
					end: '2014-05-18',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-08-30',
					end: '2015-05-31',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-08-22',
					end: '2016-05-15',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-08-20',
					end: '2017-05-28',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-19',
					end: '2018-05-20',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-08-18',
					end: '2019-05-26',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-08-24',
					end: '2020-08-02',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-09-19',
					end: '2021-05-23',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 88,
					name: 'Eredivisie',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/88.png',
				},
				{
					id: 543,
					name: 'Super Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/543.png',
				},
			],
			country: {
				name: 'Netherlands',
				code: 'NL',
				flag: 'https://media.api-sports.io/flags/nl.svg',
			},
			seasons: [
				{
					year: 2010,
					start: '2010-08-06',
					end: '2011-05-29',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-08-05',
					end: '2012-05-20',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-08-10',
					end: '2013-05-26',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-08-02',
					end: '2014-05-18',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-08-08',
					end: '2015-05-31',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-08-08',
					end: '2016-05-22',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-08-05',
					end: '2017-05-28',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-11',
					end: '2018-05-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-08-10',
					end: '2019-05-28',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-08-02',
					end: '2020-05-10',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-09-12',
					end: '2021-05-16',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 94,
					name: 'Primeira Liga',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/94.png',
				},
				{
					id: 550,
					name: 'Super Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/550.png',
				},
			],
			country: {
				name: 'Portugal',
				code: 'PT',
				flag: 'https://media.api-sports.io/flags/pt.svg',
			},

			seasons: [
				{
					year: 2010,
					start: '2010-08-13',
					end: '2011-05-14',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-08-12',
					end: '2012-05-12',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-08-17',
					end: '2013-05-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-08-16',
					end: '2014-05-11',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-08-15',
					end: '2015-05-23',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-08-14',
					end: '2016-05-15',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-08-12',
					end: '2017-05-21',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-06',
					end: '2018-05-13',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-08-10',
					end: '2019-05-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-08-09',
					end: '2020-07-26',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-09-18',
					end: '2021-05-19',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 140,
					name: 'Primera Division',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/140.png',
				},
				{
					id: 556,
					name: 'Super Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/556.png',
				},
				{
					id: 141,
					name: 'Segunda Division',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/141.png',
				},
				{
					id: 143,
					name: 'Copa del Rey',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/143.png',
				},
			],
			country: {
				name: 'Spain',
				code: 'ES',
				flag: 'https://media.api-sports.io/flags/es.svg',
			},
			seasons: [
				{
					year: 2010,
					start: '2010-08-28',
					end: '2011-05-21',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2011,
					start: '2011-08-27',
					end: '2012-05-13',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-08-18',
					end: '2013-06-01',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-08-17',
					end: '2014-05-18',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-08-23',
					end: '2015-05-23',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-08-21',
					end: '2016-05-15',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-08-19',
					end: '2017-05-21',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-18',
					end: '2018-05-20',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-08-17',
					end: '2019-05-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-08-16',
					end: '2020-07-19',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-09-12',
					end: '2021-05-23',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 205,
					name: 'TFF 2. Lig',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/205.png',
				},
				{
					name: 'Turkey',
					code: 'TR',
					flag: 'https://media.api-sports.io/flags/tr.svg',
				},
				{
					id: 552,
					name: '3. Lig - Group 1',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/552.png',
				},
			],
			country: {
				name: 'Turkey',
				code: 'TR',
				flag: 'https://media.api-sports.io/flags/tr.svg',
			},
			seasons: [
				{
					year: 2011,
					start: '2011-09-11',
					end: '2012-05-20',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2012,
					start: '2012-09-09',
					end: '2013-05-12',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-09-08',
					end: '2014-05-11',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-08-31',
					end: '2015-05-03',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-09-05',
					end: '2016-04-30',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-09-03',
					end: '2017-04-29',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-26',
					end: '2018-05-05',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-09-01',
					end: '2019-05-28',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-05-28',
					end: '2020-07-28',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-09-20',
					end: '2021-05-08',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 253,
					name: 'Major League Soccer',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/253.png',
				},
			],
			country: {
				name: 'USA',
				code: 'US',
				flag: 'https://media.api-sports.io/flags/us.svg',
			},

			seasons: [
				{
					year: 2012,
					start: '2012-03-10',
					end: '2012-12-01',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2013,
					start: '2013-03-02',
					end: '2013-12-07',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2014,
					start: '2014-03-08',
					end: '2014-12-07',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2015,
					start: '2015-03-07',
					end: '2015-12-06',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: false,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2016,
					start: '2016-03-06',
					end: '2016-12-11',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-03-04',
					end: '2017-12-09',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-03-03',
					end: '2018-12-09',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-03-02',
					end: '2019-11-10',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-02-29',
					end: '2020-12-13',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2021,
					start: '2021-04-17',
					end: '2021-11-07',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: true,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: true,
						predictions: true,
						odds: true,
					},
				},
			],
		},

		{
			league: [
				{
					id: 288,
					name: 'Premier Soccer League',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/288.png',
				},
				{
					id: 289,
					name: '1st Division',
					type: 'League',
					logo: 'https://media.api-sports.io/football/leagues/289.png',
				},
				{
					id: 507,
					name: 'Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/507.png',
				},
				{
					id: 508,
					name: 'League Cup',
					type: 'Cup',
					logo: 'https://media.api-sports.io/football/leagues/508.png',
				},
			],
			country: {
				name: 'South-Africa',
				code: 'ZA',
				flag: 'https://media.api-sports.io/flags/za.svg',
			},
			seasons: [
				{
					year: 2016,
					start: '2016-08-23',
					end: '2017-05-27',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2017,
					start: '2017-08-18',
					end: '2018-05-12',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2018,
					start: '2018-08-04',
					end: '2019-05-11',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: false,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2019,
					start: '2019-08-03',
					end: '2020-09-21',
					current: false,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: false,
					},
				},
				{
					year: 2020,
					start: '2020-10-24',
					end: '2021-05-29',
					current: true,
					coverage: {
						fixtures: {
							events: true,
							lineups: true,
							statistics_fixtures: true,
							statistics_players: false,
						},
						standings: true,
						players: true,
						top_scorers: true,
						top_assists: true,
						top_cards: true,
						injuries: false,
						predictions: true,
						odds: true,
					},
				},
			],
		},
	],
};
